name: Trivy IaC Scan (CloudFormation)

on:
  workflow_dispatch:
  push:
    inputs:
      server_ip:
        description: 'Severity'
        required: true
        default: "CRITICAL,HIGH,LOW"
        type: choice
        options:
        - CRITICAL
        - HIGH
        - MEDIUM


    branches: [ "main" ]

jobs:
  trivy-iac-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy IaC scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: "config"
          scan-ref: "."
          severity: "CRITICAL,HIGH,MEDIUM"
          format: "table"
          exit-code: "0"

